services:
  db:
    image: mysql:8.0
    container_name: mysql-workbench-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3316:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench-app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config_volume:/config
      - files_volume:/mysql_workbench_files
    ports:
      - 3009:3000
      - 3011:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  mysql_data_volume:
    driver: local
  config_volume:
    driver: local
  files_volume:
    driver: local

